// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `erc20.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:erc20.Transfer)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Transfer {
    // message fields
    // @@protoc_insertion_point(field:erc20.Transfer.from)
    pub from: ::std::string::String,
    // @@protoc_insertion_point(field:erc20.Transfer.to)
    pub to: ::std::string::String,
    // @@protoc_insertion_point(field:erc20.Transfer.amount)
    pub amount: ::std::string::String,
    // @@protoc_insertion_point(field:erc20.Transfer.token_address)
    pub token_address: ::std::string::String,
    // @@protoc_insertion_point(field:erc20.Transfer.block_number)
    pub block_number: u64,
    // special fields
    // @@protoc_insertion_point(special_field:erc20.Transfer.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Transfer {
    fn default() -> &'a Transfer {
        <Transfer as ::protobuf::Message>::default_instance()
    }
}

impl Transfer {
    pub fn new() -> Transfer {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "from",
            |m: &Transfer| { &m.from },
            |m: &mut Transfer| { &mut m.from },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "to",
            |m: &Transfer| { &m.to },
            |m: &mut Transfer| { &mut m.to },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "amount",
            |m: &Transfer| { &m.amount },
            |m: &mut Transfer| { &mut m.amount },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "token_address",
            |m: &Transfer| { &m.token_address },
            |m: &mut Transfer| { &mut m.token_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "block_number",
            |m: &Transfer| { &m.block_number },
            |m: &mut Transfer| { &mut m.block_number },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Transfer>(
            "Transfer",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Transfer {
    const NAME: &'static str = "Transfer";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.from = is.read_string()?;
                },
                18 => {
                    self.to = is.read_string()?;
                },
                26 => {
                    self.amount = is.read_string()?;
                },
                34 => {
                    self.token_address = is.read_string()?;
                },
                40 => {
                    self.block_number = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.from.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.from);
        }
        if !self.to.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.to);
        }
        if !self.amount.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.amount);
        }
        if !self.token_address.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.token_address);
        }
        if self.block_number != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.block_number);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.from.is_empty() {
            os.write_string(1, &self.from)?;
        }
        if !self.to.is_empty() {
            os.write_string(2, &self.to)?;
        }
        if !self.amount.is_empty() {
            os.write_string(3, &self.amount)?;
        }
        if !self.token_address.is_empty() {
            os.write_string(4, &self.token_address)?;
        }
        if self.block_number != 0 {
            os.write_uint64(5, self.block_number)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Transfer {
        Transfer::new()
    }

    fn clear(&mut self) {
        self.from.clear();
        self.to.clear();
        self.amount.clear();
        self.token_address.clear();
        self.block_number = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Transfer {
        static instance: Transfer = Transfer {
            from: ::std::string::String::new(),
            to: ::std::string::String::new(),
            amount: ::std::string::String::new(),
            token_address: ::std::string::String::new(),
            block_number: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Transfer {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Transfer").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Transfer {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Transfer {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0berc20.proto\x12\x05erc20\"\x8e\x01\n\x08Transfer\x12\x12\n\x04from\
    \x18\x01\x20\x01(\tR\x04from\x12\x0e\n\x02to\x18\x02\x20\x01(\tR\x02to\
    \x12\x16\n\x06amount\x18\x03\x20\x01(\tR\x06amount\x12#\n\rtoken_address\
    \x18\x04\x20\x01(\tR\x0ctokenAddress\x12!\n\x0cblock_number\x18\x05\x20\
    \x01(\x04R\x0bblockNumberJ\xc7\x02\n\x06\x12\x04\0\0\n\x01\n\x08\n\x01\
    \x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x0e\n\n\n\x02\x04\0\
    \x12\x04\x04\0\n\x01\n\n\n\x03\x04\0\x01\x12\x03\x04\x08\x10\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03\x05\x02\x12\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x05\
    \x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x05\t\r\n\x0c\n\x05\x04\0\
    \x02\0\x03\x12\x03\x05\x10\x11\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x06\x02\
    \x10\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x06\x02\x08\n\x0c\n\x05\x04\0\
    \x02\x01\x01\x12\x03\x06\t\x0b\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x06\
    \x0e\x0f\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x07\x02\x14\n\x0c\n\x05\x04\0\
    \x02\x02\x05\x12\x03\x07\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\
    \x07\t\x0f\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x07\x12\x13\n\x0b\n\x04\
    \x04\0\x02\x03\x12\x03\x08\x02\x1b\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\
    \x08\x02\x08\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\x08\t\x16\n\x0c\n\x05\
    \x04\0\x02\x03\x03\x12\x03\x08\x19\x1a\n\x0b\n\x04\x04\0\x02\x04\x12\x03\
    \t\x02\x1a\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\t\x02\x08\n\x0c\n\x05\
    \x04\0\x02\x04\x01\x12\x03\t\t\x15\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\
    \t\x18\x19b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Transfer::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
